// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachPlanner.Shared.Database;

#nullable disable

namespace TeachPlanner.Shared.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalendarSchoolEvent", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolEventsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CalendarId", "SchoolEventsId");

                    b.HasIndex("SchoolEventsId");

                    b.ToTable("CalendarSchoolEvent");
                });

            modelBuilder.Entity("CurriculumSubjectTeacher", b =>
                {
                    b.Property<Guid>("SubjectsTaughtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubjectsTaughtId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CurriculumSubjectTeacher");
                });

            modelBuilder.Entity("DayPlanSchoolEvent", b =>
                {
                    b.Property<Guid>("DayPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolEventsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DayPlanId", "SchoolEventsId");

                    b.HasIndex("SchoolEventsId");

                    b.ToTable("DayPlanSchoolEvent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DateConducted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LessonPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanningNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("LessonPlanId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Calendar.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TermEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("TermStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("calendar", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Common.Planner.SchoolEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FullDay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("school_events", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.ContentDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("StrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Substrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StrandId");

                    b.ToTable("content_descriptions", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TermPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TermPlanId");

                    b.ToTable("curriculum_subjects", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.Elaboration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentDescriptionId");

                    b.ToTable("elaborations", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.Strand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("YearLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YearLevelId");

                    b.ToTable("strands", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.YearLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AchievementStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BandLevelValue")
                        .HasColumnType("int");

                    b.Property<Guid>("CurriculumSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("YearLevelDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearLevelValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumSubjectId");

                    b.ToTable("year_levels", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.LessonPlans.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("LessonDate")
                        .HasColumnType("date");

                    b.Property<int>("NumberOfPeriods")
                        .HasColumnType("int");

                    b.Property<string>("PlanningNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartPeriod")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WeekPlannerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WeekPlannerId");

                    b.HasIndex("YearDataId");

                    b.ToTable("lesson_plans", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.LessonPlans.LessonPlanResource", b =>
                {
                    b.Property<Guid>("LessonPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonPlanId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("lesson_plan_resources", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.PlannerTemplates.DayPlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("day_plan_templates", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.PlannerTemplates.TermDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("term_dates", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("YearDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearDataId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Teachers.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AssociatedStrands")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAssessment")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Teachers.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.TermPlanners.TermPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TermPlannerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TermPlannerId");

                    b.ToTable("term_plans", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.TermPlanners.TermPlanner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_yearLevels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YearLevels");

                    b.HasKey("Id");

                    b.HasIndex("YearDataId")
                        .IsUnique();

                    b.ToTable("term_planner", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.WeekPlanners.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("WeekPlannerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WeekPlannerId");

                    b.ToTable("day_plans", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.WeekPlanners.WeekPlanner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayPlanTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayPlanTemplateId");

                    b.HasIndex("YearDataId");

                    b.ToTable("week_planner", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.YearDataRecords.YearData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<Guid>("DayPlanTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TermPlannerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_yearLevelsTaught")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("YearLevels");

                    b.HasKey("Id");

                    b.HasIndex("DayPlanTemplateId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermPlannerId")
                        .IsUnique()
                        .HasFilter("[TermPlannerId] IS NOT NULL");

                    b.ToTable("yeardata", (string)null);
                });

            modelBuilder.Entity("CalendarSchoolEvent", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Calendar.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Common.Planner.SchoolEvent", null)
                        .WithMany()
                        .HasForeignKey("SchoolEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CurriculumSubjectTeacher", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsTaughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DayPlanSchoolEvent", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.WeekPlanners.DayPlan", null)
                        .WithMany()
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Common.Planner.SchoolEvent", null)
                        .WithMany()
                        .HasForeignKey("SchoolEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Assessments.Assessment", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.LessonPlans.LessonPlan", null)
                        .WithMany("Assessments")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Students.Student", null)
                        .WithMany("Assessments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany("Assessments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TeachPlanner.Shared.Domain.Assessments.AssessmentResult", "AssessmentResult", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Comments")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DateMarked")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("UpdatedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id", "AssessmentId");

                            b1.HasIndex("AssessmentId")
                                .IsUnique();

                            b1.ToTable("assessment_results", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");

                            b1.OwnsOne("TeachPlanner.Shared.Domain.Assessments.AssessmentGrade", "Grade", b2 =>
                                {
                                    b2.Property<Guid>("AssessmentResultId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("AssessmentResultAssessmentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Grade")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)");

                                    b2.Property<double?>("Percentage")
                                        .IsRequired()
                                        .HasColumnType("float")
                                        .HasColumnName("Percentage");

                                    b2.HasKey("AssessmentResultId", "AssessmentResultAssessmentId");

                                    b2.ToTable("assessment_results");

                                    b2.WithOwner()
                                        .HasForeignKey("AssessmentResultId", "AssessmentResultAssessmentId");
                                });

                            b1.Navigation("Grade")
                                .IsRequired();
                        });

                    b.Navigation("AssessmentResult");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Common.Planner.SchoolEvent", b =>
                {
                    b.OwnsOne("TeachPlanner.Shared.Domain.Common.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("SchoolEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Suburb")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("SchoolEventId");

                            b1.ToTable("school_events");

                            b1.WithOwner()
                                .HasForeignKey("SchoolEventId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.ContentDescription", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.Strand", null)
                        .WithMany("ContentDescriptions")
                        .HasForeignKey("StrandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.TermPlanners.TermPlan", null)
                        .WithMany("Subjects")
                        .HasForeignKey("TermPlanId");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.Elaboration", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.ContentDescription", null)
                        .WithMany("Elaborations")
                        .HasForeignKey("ContentDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.Strand", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.YearLevel", null)
                        .WithMany("Strands")
                        .HasForeignKey("YearLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.YearLevel", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", null)
                        .WithMany("YearLevels")
                        .HasForeignKey("CurriculumSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.LessonPlans.LessonPlan", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.WeekPlanners.DayPlan", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("WeekPlannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.YearDataRecords.YearData", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("YearDataId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Shared.Domain.LessonPlans.LessonComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LessonPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Completed")
                                .HasColumnType("bit");

                            b1.Property<DateTime?>("CompletedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("StruckOut")
                                .HasColumnType("bit");

                            b1.Property<DateTime>("UpdatedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id", "LessonPlanId");

                            b1.HasIndex("LessonPlanId");

                            b1.ToTable("lesson_comment", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LessonPlanId");
                        });

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.LessonPlans.LessonPlanResource", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.LessonPlans.LessonPlan", null)
                        .WithMany("LessonPlanResources")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Resource", null)
                        .WithMany("LessonPlanResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.PlannerTemplates.DayPlanTemplate", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Shared.Domain.PlannerTemplates.TemplatePeriod", "Periods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("DayPlanTemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PeriodType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time");

                            b1.HasKey("Id");

                            b1.HasIndex("DayPlanTemplateId");

                            b1.ToTable("template_periods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DayPlanTemplateId");
                        });

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Reports.Report", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Students.Student", null)
                        .WithMany("Reports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Shared.Domain.Reports.ReportComment", "ReportComments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CharacterLimit")
                                .HasColumnType("int");

                            b1.Property<string>("Comments")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Grade")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportId");

                            b1.ToTable("report_comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("ReportComments");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Students.Student", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.YearDataRecords.YearData", null)
                        .WithMany("Students")
                        .HasForeignKey("YearDataId");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Teachers.Resource", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany("Resources")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Teachers.Teacher", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.Users.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TeachPlanner.Shared.Domain.Teachers.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Shared.Domain.Teachers.YearDataEntry", "YearDataHistory", b1 =>
                        {
                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CalendarYear")
                                .HasColumnType("int")
                                .HasColumnName("CalendarYear");

                            b1.Property<Guid>("YearDataId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("YearDataId");

                            b1.HasKey("TeacherId", "Id");

                            b1.ToTable("year_data_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeacherId");
                        });

                    b.Navigation("YearDataHistory");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.TermPlanners.TermPlan", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.TermPlanners.TermPlanner", "TermPlanner")
                        .WithMany("TermPlans")
                        .HasForeignKey("TermPlannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermPlanner");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.TermPlanners.TermPlanner", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.YearDataRecords.YearData", null)
                        .WithOne()
                        .HasForeignKey("TeachPlanner.Shared.Domain.TermPlanners.TermPlanner", "YearDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.WeekPlanners.DayPlan", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.WeekPlanners.WeekPlanner", null)
                        .WithMany("DayPlans")
                        .HasForeignKey("WeekPlannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.WeekPlanners.WeekPlanner", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.PlannerTemplates.DayPlanTemplate", null)
                        .WithMany()
                        .HasForeignKey("DayPlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.YearDataRecords.YearData", null)
                        .WithMany("WeekPlanners")
                        .HasForeignKey("YearDataId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.YearDataRecords.YearData", b =>
                {
                    b.HasOne("TeachPlanner.Shared.Domain.PlannerTemplates.DayPlanTemplate", "DayPlanTemplate")
                        .WithMany()
                        .HasForeignKey("DayPlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Shared.Domain.TermPlanners.TermPlanner", null)
                        .WithOne()
                        .HasForeignKey("TeachPlanner.Shared.Domain.YearDataRecords.YearData", "TermPlannerId");

                    b.OwnsMany("TeachPlanner.Shared.Domain.YearDataRecords.Subject", "Subjects", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.Property<Guid>("YearDataId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("YearDataId");

                            b1.ToTable("subjects", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("YearDataId");

                            b1.OwnsMany("TeachPlanner.Shared.Domain.YearDataRecords.YearDataContentDescription", "ContentDescriptions", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CurriculumCode")
                                        .IsRequired()
                                        .HasMaxLength(15)
                                        .HasColumnType("nvarchar(15)");

                                    b2.Property<Guid>("SubjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SubjectId");

                                    b2.ToTable("year_data_content_descriptions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SubjectId");
                                });

                            b1.Navigation("ContentDescriptions");
                        });

                    b.Navigation("DayPlanTemplate");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.ContentDescription", b =>
                {
                    b.Navigation("Elaborations");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.CurriculumSubject", b =>
                {
                    b.Navigation("YearLevels");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.Strand", b =>
                {
                    b.Navigation("ContentDescriptions");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Curriculum.YearLevel", b =>
                {
                    b.Navigation("Strands");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.LessonPlans.LessonPlan", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("LessonPlanResources");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Students.Student", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Teachers.Resource", b =>
                {
                    b.Navigation("LessonPlanResources");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.Teachers.Teacher", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.TermPlanners.TermPlan", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.TermPlanners.TermPlanner", b =>
                {
                    b.Navigation("TermPlans");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.WeekPlanners.DayPlan", b =>
                {
                    b.Navigation("LessonPlans");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.WeekPlanners.WeekPlanner", b =>
                {
                    b.Navigation("DayPlans");
                });

            modelBuilder.Entity("TeachPlanner.Shared.Domain.YearDataRecords.YearData", b =>
                {
                    b.Navigation("LessonPlans");

                    b.Navigation("Students");

                    b.Navigation("WeekPlanners");
                });
#pragma warning restore 612, 618
        }
    }
}
