// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachPlanner.Api.Database;

#nullable disable

namespace TeachPlanner.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231006104749_RemovedSubstrands")]
    partial class RemovedSubstrands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CalendarSchoolEvent", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SchoolEventsId")
                        .HasColumnType("char(36)");

                    b.HasKey("CalendarId", "SchoolEventsId");

                    b.HasIndex("SchoolEventsId");

                    b.ToTable("CalendarSchoolEvent");
                });

            modelBuilder.Entity("SchoolEventWeekPlanner", b =>
                {
                    b.Property<Guid>("SchoolEventsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WeekPlannerId")
                        .HasColumnType("char(36)");

                    b.HasKey("SchoolEventsId", "WeekPlannerId");

                    b.HasIndex("WeekPlannerId");

                    b.ToTable("SchoolEventWeekPlanner");
                });

            modelBuilder.Entity("SubjectYearData", b =>
                {
                    b.Property<Guid>("SubjectsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubjectsId", "YearDataId");

                    b.HasIndex("YearDataId");

                    b.ToTable("SubjectYearData");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.AssessmentIds.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("ConductedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LessonPlanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PlanningNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("LessonPlanId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Calendar.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TermEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("TermStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("calendar", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Common.Planner.SchoolEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FullDay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("school_events", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.LessonPlans.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfPeriods")
                        .HasColumnType("int");

                    b.Property<string>("PlanningNotes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("WeekPlannerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WeekPlannerId");

                    b.HasIndex("YearDataId");

                    b.ToTable("lesson_plans", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.LessonPlans.LessonPlanResource", b =>
                {
                    b.Property<Guid>("LessonPlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("char(36)");

                    b.HasKey("LessonPlanId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("lesson_plan_resources", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("char(36)");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearDataId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Resources.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("AssociatedStrands")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAssessment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("YearDataId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearDataId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurriculumSubject")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("TermPlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TermPlanId");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Teachers.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.TermPlanners.TermPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TermPlannerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TermPlannerId");

                    b.ToTable("term_plans", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.TermPlanners.TermPlanner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("char(36)");

                    b.Property<string>("_yearLevels")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("YearLevels");

                    b.HasKey("Id");

                    b.HasIndex("YearDataId")
                        .IsUnique();

                    b.ToTable("term_planner", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.WeekPlanners.WeekPlanner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("YearDataId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("YearDataId");

                    b.ToTable("week_planner", (string)null);
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.YearDataRecords.YearData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TermPlannerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("_yearLevelsTaught")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("YearLevels");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermPlannerId")
                        .IsUnique();

                    b.ToTable("yeardata", (string)null);
                });

            modelBuilder.Entity("CalendarSchoolEvent", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Calendar.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Common.Planner.SchoolEvent", null)
                        .WithMany()
                        .HasForeignKey("SchoolEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolEventWeekPlanner", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Common.Planner.SchoolEvent", null)
                        .WithMany()
                        .HasForeignKey("SchoolEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.WeekPlanners.WeekPlanner", null)
                        .WithMany()
                        .HasForeignKey("WeekPlannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubjectYearData", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.YearDataRecords.YearData", null)
                        .WithMany()
                        .HasForeignKey("YearDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.AssessmentIds.Assessment", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.LessonPlans.LessonPlan", null)
                        .WithMany("AssessmentIds")
                        .HasForeignKey("LessonPlanId");

                    b.HasOne("TeachPlanner.Api.Domain.Students.Student", null)
                        .WithMany("AssessmentIds")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Teachers.Teacher", null)
                        .WithMany("AssessmentIds")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TeachPlanner.Api.Domain.AssessmentIds.AssessmentResult", "AssessmentResult", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Comments")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("varchar(1000)");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("DateMarked")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("UpdatedDateTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id", "AssessmentId");

                            b1.HasIndex("AssessmentId")
                                .IsUnique();

                            b1.ToTable("assessment_results", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");

                            b1.OwnsOne("TeachPlanner.Api.Domain.AssessmentIds.AssessmentGrade", "Grade", b2 =>
                                {
                                    b2.Property<Guid>("AssessmentResultId")
                                        .HasColumnType("char(36)");

                                    b2.Property<Guid>("AssessmentResultAssessmentId")
                                        .HasColumnType("char(36)");

                                    b2.Property<string>("Grade")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("varchar(10)");

                                    b2.Property<double?>("Percentage")
                                        .IsRequired()
                                        .HasColumnType("double")
                                        .HasColumnName("Percentage");

                                    b2.HasKey("AssessmentResultId", "AssessmentResultAssessmentId");

                                    b2.ToTable("assessment_results");

                                    b2.WithOwner()
                                        .HasForeignKey("AssessmentResultId", "AssessmentResultAssessmentId");
                                });

                            b1.Navigation("Grade")
                                .IsRequired();
                        });

                    b.Navigation("AssessmentResult");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Common.Planner.SchoolEvent", b =>
                {
                    b.OwnsOne("TeachPlanner.Api.Domain.Common.Planner.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("SchoolEventId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Suburb")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("SchoolEventId");

                            b1.ToTable("school_events");

                            b1.WithOwner()
                                .HasForeignKey("SchoolEventId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.LessonPlans.LessonPlan", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.WeekPlanners.WeekPlanner", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("WeekPlannerId");

                    b.HasOne("TeachPlanner.Api.Domain.YearDataRecords.YearData", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("YearDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Api.Domain.LessonPlans.LessonComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("LessonPlanId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("Completed")
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime?>("CompletedDateTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<DateTime>("CreatedDateTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<bool>("StruckOut")
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime>("UpdatedDateTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id", "LessonPlanId");

                            b1.HasIndex("LessonPlanId");

                            b1.ToTable("lesson_comment", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LessonPlanId");
                        });

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.LessonPlans.LessonPlanResource", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.LessonPlans.LessonPlan", null)
                        .WithMany("LessonPlanResources")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Resources.Resource", null)
                        .WithMany("LessonPlanResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Reports.Report", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Students.Student", null)
                        .WithMany("Reports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.YearDataRecords.YearData", null)
                        .WithMany("Reports")
                        .HasForeignKey("YearDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Api.Domain.Reports.ReportComment", "ReportComments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<int>("CharacterLimit")
                                .HasColumnType("int");

                            b1.Property<string>("Comments")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.Property<string>("Grade")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");

                            b1.Property<Guid>("ReportId")
                                .HasColumnType("char(36)");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportId");

                            b1.ToTable("report_comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("ReportComments");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Resources.Resource", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.Teachers.Teacher", null)
                        .WithMany("Resources")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Students.Student", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.YearDataRecords.YearData", null)
                        .WithMany("Students")
                        .HasForeignKey("YearDataId");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Subjects.Subject", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.TermPlanners.TermPlan", null)
                        .WithMany("Subjects")
                        .HasForeignKey("TermPlanId");

                    b.OwnsMany("TeachPlanner.Api.Domain.Subjects.YearLevel", "YearLevels", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("AchievementStandard")
                                .HasColumnType("longtext");

                            b1.Property<int?>("BandLevelValue")
                                .HasColumnType("int");

                            b1.Property<Guid>("SubjectId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("YearLevelDescription")
                                .HasColumnType("longtext");

                            b1.Property<int?>("YearLevelValue")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("SubjectId");

                            b1.ToTable("year_levels", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubjectId");

                            b1.OwnsMany("TeachPlanner.Api.Domain.Subjects.Strand", "Strands", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("char(36)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("varchar(50)");

                                    b2.Property<Guid>("YearLevelId")
                                        .HasColumnType("char(36)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("YearLevelId");

                                    b2.ToTable("strands", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("YearLevelId");

                                    b2.OwnsMany("TeachPlanner.Api.Domain.Subjects.ContentDescription", "ContentDescriptions", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("char(36)");

                                            b3.Property<string>("CurriculumCode")
                                                .IsRequired()
                                                .HasMaxLength(50)
                                                .HasColumnType("varchar(50)");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasMaxLength(1000)
                                                .HasColumnType("varchar(1000)");

                                            b3.Property<Guid>("StrandId")
                                                .HasColumnType("char(36)");

                                            b3.Property<string>("Substrand")
                                                .IsRequired()
                                                .HasColumnType("longtext");

                                            b3.HasKey("Id");

                                            b3.HasIndex("StrandId");

                                            b3.ToTable("content_descriptions", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("StrandId");

                                            b3.OwnsMany("TeachPlanner.Api.Domain.Subjects.Elaboration", "Elaborations", b4 =>
                                                {
                                                    b4.Property<Guid>("Id")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("char(36)");

                                                    b4.Property<Guid>("ContentDescriptionId")
                                                        .HasColumnType("char(36)");

                                                    b4.Property<string>("Description")
                                                        .IsRequired()
                                                        .HasMaxLength(1000)
                                                        .HasColumnType("varchar(1000)");

                                                    b4.HasKey("Id");

                                                    b4.HasIndex("ContentDescriptionId");

                                                    b4.ToTable("elaborations", (string)null);

                                                    b4.WithOwner()
                                                        .HasForeignKey("ContentDescriptionId");
                                                });

                                            b3.Navigation("Elaborations");
                                        });

                                    b2.Navigation("ContentDescriptions");
                                });

                            b1.Navigation("Strands");
                        });

                    b.Navigation("YearLevels");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Teachers.Teacher", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("TeachPlanner.Api.Domain.Teachers.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TeachPlanner.Api.Domain.Teachers.YearDataEntry", "YearDataHistory", b1 =>
                        {
                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<int>("CalendarYear")
                                .HasColumnType("int")
                                .HasColumnName("CalendarYear");

                            b1.Property<Guid>("YearDataId")
                                .HasColumnType("char(36)")
                                .HasColumnName("YearDataId");

                            b1.HasKey("TeacherId", "Id");

                            b1.ToTable("year_data_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeacherId");
                        });

                    b.Navigation("YearDataHistory");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.TermPlanners.TermPlan", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.TermPlanners.TermPlanner", "TermPlanner")
                        .WithMany("TermPlans")
                        .HasForeignKey("TermPlannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermPlanner");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.TermPlanners.TermPlanner", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.YearDataRecords.YearData", null)
                        .WithOne()
                        .HasForeignKey("TeachPlanner.Api.Domain.TermPlanners.TermPlanner", "YearDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.WeekPlanners.WeekPlanner", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Calendar.Calendar", null)
                        .WithMany("WeekPlanners")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.YearDataRecords.YearData", null)
                        .WithMany("WeekPlanners")
                        .HasForeignKey("YearDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.YearDataRecords.YearData", b =>
                {
                    b.HasOne("TeachPlanner.Api.Domain.Teachers.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachPlanner.Api.Domain.TermPlanners.TermPlanner", null)
                        .WithOne()
                        .HasForeignKey("TeachPlanner.Api.Domain.YearDataRecords.YearData", "TermPlannerId");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Calendar.Calendar", b =>
                {
                    b.Navigation("WeekPlanners");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.LessonPlans.LessonPlan", b =>
                {
                    b.Navigation("AssessmentIds");

                    b.Navigation("LessonPlanResources");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Resources.Resource", b =>
                {
                    b.Navigation("LessonPlanResources");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Students.Student", b =>
                {
                    b.Navigation("AssessmentIds");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.Teachers.Teacher", b =>
                {
                    b.Navigation("AssessmentIds");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.TermPlanners.TermPlan", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.TermPlanners.TermPlanner", b =>
                {
                    b.Navigation("TermPlans");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.WeekPlanners.WeekPlanner", b =>
                {
                    b.Navigation("LessonPlans");
                });

            modelBuilder.Entity("TeachPlanner.Api.Domain.YearDataRecords.YearData", b =>
                {
                    b.Navigation("LessonPlans");

                    b.Navigation("Reports");

                    b.Navigation("Students");

                    b.Navigation("WeekPlanners");
                });
#pragma warning restore 612, 618
        }
    }
}
